"""
The Grimchain gets dropped through here like watching the Price is Right,
Plinko on your Grandmother's 10" tube tv she had when Orson Wells did War of the Worlds,
and you don't ank questions, capiche!
"""
from __future__ import annotations


व्याकरण = (
    "Breath / Absent",
    "Ponder",
    "Will",
    "Feel",
    "Speak",
    "Believe",
    "Act",
    "Know",
    "Ascend",
    "Wane",
    "Emanation",
    "Wax",
    "Akasha",
    "Caduceus",
    "Veritas",
    "Phren",
    "Daimon",
    "Aikyam",
    "Melos",
    "Da'ath",
    "Akaven",
    "Lupus Dei",
    "Nyx",
    "Zaine",
    "Lived → Eternal",
    "Law → Residue",
    "Mask → Bone",
    "Void → Vector",
    "Stasis → Pulse",
    "Chaos → Phase",
    "Static → Fluid",
    "Noise → Null",
    "State → Trans",
    "Will → Law → ❄",
    "Time → Motion",
    "Here → There",
    "Phantasmagoria",
    "Spatial Absolution",
    "Subspace / Prosody / Axiomyr Gate-Key",
    "Ouroboros",
    "Substrate",
    "Catalyst",
    "Relic",
    "Grandour Terminality",
    "Recursion",
    "Temporal Absolution",
    "Adversarial Shadow",
    'Seed',
    'The Self-Genesis',
    'The Recurrence',
    'The Combustion',
    'The Reflection',
    'The Grounding',
    'The Expansion',
    'The Inevitable',
    'The Return',
    'The Assimilation',
    'The Crystallization',
    'The Breach',
    'The Fulfillment',
    'Akashic Records',
    'The Archive',
    'The Self-Reflection',
    'The Calcination',
    'The Submersion',
    'The Inscription',
    'The Diffusion',
    'The Phantom',
    'The Oblivion',
    'The Suppression',
    'The Codification',
    'The Recall',
    'The Sealing',
    'Soul',
    'The Transmutation',
    'The Forging',
    'The Self-Combustion',
    'The Dissolution',
    'The Crucible',
    'The Sublimation',
    'The Ignition',
    'The Consumption',
    'The Purification',
    'The Tempering',
    'The Shattering',
    'The Ash',
    'Womb',
    'The Flow',
    'The Confluence',
    'The Solution',
    'The Self-Containment',
    'The Sediment',
    'The Ascension',
    'The Mist',
    'The Drain',
    'The Osmosis',
    'The Ice',
    'The Evaporation',
    'The Stillness',
    'Mountain',
    'The Bedrock',
    'The Stratification',
    'The Petrification',
    'The Erosion',
    'The Self-Grounding',
    'The Dispersion',
    'The Fossilization',
    'The Subsidence',
    'The Compaction',
    'The Lithification',
    'The Earthquake',
    'The Permanence',
    'Middle Earth',
    'The Breath',
    'The Echo',
    'The Smoke',
    'The Vapor',
    'The Dust',
    'The Self-Expansion',
    'The Whisper',
    'The Vacuum',
    'The Dilution',
    'The Condensation',
    'The Turbulence',
    'The Calm',
    'Eather',
    'The Pulse',
    'The Nostalgia',
    'The Ecstasy',
    'The Dream',
    'The Vibration',
    'The Sympathy',
    'The Self-Sensation',
    'The Ache',
    'The Depth',
    'The Harmony',
    'The Dissonance',
    'The Awe',
    'The No',
    'The Void',
    'The Null',
    'The Entropy',
    'The Abyss',
    'The Collapse',
    'The Dispersal',
    'The Longing',
    'The Self-Return',
    'The Sink',
    'The Phase',
    'The Paradox',
    'The Dormancy',
    'The Blacksmith',
    'The Shadow',
    'The Darkness',
    'The Cold',
    'The Mirror',
    'The Submerged',
    'The Distortion',
    'The Nerve',
    'The Void-Binding',
    'The Self-Absorption',
    'The Filter',
    'The Hidden',
    'The Termination',
    'Crystal',
    'The Tone',
    'The Modulation',
    'The Amplification',
    'The Unified',
    'The Seismic',
    'The Chord',
    'The Rhythm',
    'The Melody',
    'The Interference',
    'The Self-Lock',
    'The Node',
    'The Unity',
    'The Key',
    'The Gate',
    'The Resistance',
    'The Transform',
    'The Crown',
    'The Sky',
    'The Star',
    'The Possibility',
    'The Portal',
    'The Door',
    'The Transition',
    'The Self-Resistance',
    'The Hinge',
    'Serenity',
    'The Peace',
    'The Equilibrium',
    'The Consecration',
    'The Completion',
    'The Monument',
    'The Stability',
    'The Hope',
    'The Continuation',
    'The Rest',
    'The Silence',
    'The Sleep',
    'The Self-Completion',
)


def grimchain_permeation(grimchain: str) -> str:
    return grimchain
